name: CI/CD C++ Module

on:
  push:
    branches: [ "main", "3-github-action-cicd-pipeline" ]
    paths: ["cpp-engine/**", '.github/workflows/cpp-pipeline.yml']
  pull_request:
    branches: [ "main"  ]
    types: [opened, synchronize, reopened]

jobs:
  cpp-build-test:
    name: C++ Build & Test (${{ matrix.os }} - ${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache CMake deps
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: cpp-engine/build/_deps
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Configure and Build
      run: |
        cd cpp-engine
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build --config ${{ matrix.build_type }}

    - name: Run Tests 
      working-directory: cpp-engine/build/
      run: ctest --output-on-failure
        
    # Static analysis
    - name: Run clang-tidy
      if: runner.os == 'Linux'
      continue-on-error: true
      run: |
        clang-tidy cpp-engine/src/*.cpp -p cpp-engine/build || true

    # Generate JSON
    - name: Generate report
      if: 
      run: |
        cd cpp-engine
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./build/engine.exe ../data/transactions.csv > report.json
        else
          ./build/engine ../data/transactions.csv > report.json
        fi
      shell: bash

    #summary 
    - name: Summary
      if: always()
      run: |
        echo "✅ C++ Pipeline Result" >> $GITHUB_STEP_SUMMARY
        echo "OS: ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "Build: ${{ matrix.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY